name: Permaculture
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49225
title: An Adventure in permaculture.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf1f7'
    - '#090b0a'
    - '#827e7b'
    - '#454640'
    - '#afcee0'
  brandStrength: 0.5
  lightness: 0.4583050855435431
  saturation: 0.1344085216987878
  rhythmicContrast: 0.3475228368770331
purpose: []
