name: Permaculture
favicon: null
layout_spectrum: 0.012273649452254176
typography_spectrum: 0.3838753628078848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.09575844532810152
  lightness: 0.4583050855435431
  saturation: 0.1344085216987878
  rhythmicContrast: 0.3475228368770331
purpose: []
